### ISSUE TITLE
Improve User Experience

### ISSUE THREAD

**Issue by sunandabalu** [dotnet/upgrade-assistant#1085]
- [ ] Users think the tool is hung when a long running operation is being performed, provide feedback on status to the user.
- [ ] Identify top 10 error messages we see generated from user code then add those links to UA
- [ ] Documentation for UA specific error messages (for the tool itself)
- [ ] Find the right doc for each tech placement: System.Web, WCF, UWP, C++/CLI project replacement options in the tool - add links to UA
- [ ] Elevate how to run in verbose mode or how to suppress more messages

**Comment by sunandabalu** [comment]
These items were identified in the Customer Survey
